apiVersion: v1
kind: Service
metadata:
  name: nodejs-backend
  #  annotations:
  # alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  selector:
    app: nodejs-backend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
